name: Github Labeler
description: A Github Action to label your issues, prs and discussions with additional info
author: twsl

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: purple

# Define your inputs here.
inputs:
  github-token:
    description: "GitHub access token"
    default: "${{ github.token }}"

  config-path:
    description: "Configuration file path"
    default: ".github/gh-labeler.yaml"

  milliseconds:
    description: Your input description here
    required: true
    default: "1000"

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
