name: Github Labeler
description: >-
  A GitHub Action to label issues, pull requests, and discussions with
  additional metadata.
author: twsl
# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: purple

# Define your inputs here.
inputs:
  github-token:
    description: "GitHub access token"
    default: "${{ github.token }}"

  config-path:
    description: "Configuration file path"
    default: ".github/gh-labeler.yaml"

  process:
    description: "Process to run (issue, pr, discussion)"
    default: |
      issue
      pr
      discussion

# Define your outputs here.
outputs:
  duration:
    description: Duration of the action execution

runs:
  using: node20
  main: dist/index.js
